### ISSUE TITLE
Please upload 0.3.4 on releases

### ISSUE THREAD

**Issue by kenhys** [mattn/gntp-send#11]
As growl-for-linux is now packaged into Debian/unstable and testing, so I'm also trying to begin Debian ITP process as same as growl-for-linux in next step.

I'm happy if you upload gntp-send-0.3.4.tar.gz and signed gntp-send-0.3.4.tar.gz.asc files to https://github.com/mattn/gntp-send/releases.

**Comment by mattn** [comment]
https://github.com/mattn/gntp-send/releases/tag/0.3.4

done.

**Comment by kenhys** [comment]
Thanks!

I did ITP and RFS procedure.

ITP:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829331
RFS:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829333

**Comment by kenhys** [comment]
FYI: gntp-send is now available on Debian unstable.

https://packages.debian.org/search?suite=sid&searchon=names&keywords=gntp-send
